language: rust
rust: nightly

before_install:
  - export AUG_VERSION="1.3.0"
  - wget "http://download.augeas.net/augeas-${AUG_VERSION}.tar.gz"
  - tar -xvf augeas-${AUG_VERSION}.tar.gz
  - cd "augeas-${AUG_VERSION}"
  - ./configure --prefix=/usr
  - make
  - sudo make install
